export interface XMartTableDefinition {
    CODE: string;
    TITLE: string;
}

export interface XMartFieldDefinition {
    TABLE_CODE: string;
    CODE: string;
    TITLE: string;
    FIELD_TYPE_CODE: string;
    IS_REQUIRED: "Y" | "N";
    IS_PRIMARY_KEY: "Y" | "N";
    IS_ROW_TITLE: "Y" | "N";
}

export interface xMartTable {
    table: XMartTableDefinition;
    fields: XMartFieldDefinition[];
}

export type xMartTableKey = "dataValues" | "events" | "eventValues" | "teis" | "teiAttributes" | "enrollments";

export const xMartSyncTables: Record<xMartTableKey, xMartTable> = {
    dataValues: {
        table: { CODE: "DATA_VALUES", TITLE: "Events" },
        fields: [
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "value",
                TITLE: "Value",
                FIELD_TYPE_CODE: "TEXT_MAX",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "period",
                TITLE: "Period",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "orgUnit",
                TITLE: "Organisation Unit",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "dataElement",
                TITLE: "Data Element",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "attributeOptionCombo",
                TITLE: "Attribute Option Combo",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "categoryOptionCombo",
                TITLE: "Category Option Combo",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
    events: {
        table: { CODE: "EVENTS", TITLE: "Events" },
        fields: [
            {
                TABLE_CODE: "EVENTS",
                CODE: "event",
                TITLE: "Event",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "program",
                TITLE: "Program",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "programStage",
                TITLE: "Program Stage",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "orgUnit",
                TITLE: "Organisation Unit",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "enrollment",
                TITLE: "Enrollment",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "attributeCategoryOptions",
                TITLE: "Attribute Category Options",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "attributeOptionCombo",
                TITLE: "Attribute Option Combo",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "dueDate",
                TITLE: "Due Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "DATA_VALUES",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
    eventValues: {
        table: { CODE: "EVENT_VALUES", TITLE: "Event Values" },
        fields: [
            {
                TABLE_CODE: "EVENT_VALUES",
                CODE: "event",
                TITLE: "Event",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENT_VALUES",
                CODE: "dataElement",
                TITLE: "Data Element",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENT_VALUES",
                CODE: "value",
                TITLE: "Value",
                FIELD_TYPE_CODE: "TEXT_MAX",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENT_VALUES",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
    teis: {
        table: { CODE: "TRACKED_ENTITY_INSTANCES", TITLE: "Tracked Entity Instances" },
        fields: [
            {
                TABLE_CODE: "TRACKED_ENTITY_INSTANCES",
                CODE: "trackedEntityInstance",
                TITLE: "Tracked Entity Instance",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TRACKED_ENTITY_INSTANCES",
                CODE: "trackedEntityType",
                TITLE: "Tracked Entity Type",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TRACKED_ENTITY_INSTANCES",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
    teiAttributes: {
        table: { CODE: "TEI_ATTRIBUTES", TITLE: "TEI Attributes" },
        fields: [
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "trackedentityInstance",
                TITLE: "Tracked EntityInstance",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "attribute",
                TITLE: "Attribute",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "code",
                TITLE: "Code",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "displayName",
                TITLE: "Display Name",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "value",
                TITLE: "Value",
                FIELD_TYPE_CODE: "TEXT_MAX",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "TEI_ATTRIBUTES",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
    enrollments: {
        table: { CODE: "ENROLLMENTS", TITLE: "Enrollments" },
        fields: [
            {
                TABLE_CODE: "ENROLLMENTS",
                CODE: "enrollment",
                TITLE: "Enrollment",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "Y",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "ENROLLMENTS",
                CODE: "trackedEntityInstance",
                TITLE: "Tracked Entity Instance",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "program",
                TITLE: "Program",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "EVENTS",
                CODE: "orgUnit",
                TITLE: "Organisation Unit",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "ENROLLMENTS",
                CODE: "created",
                TITLE: "Created Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
            {
                TABLE_CODE: "ENROLLMENTS",
                CODE: "enrollmentDate",
                TITLE: "Enrollment Date",
                FIELD_TYPE_CODE: "TEXT_50",
                IS_REQUIRED: "Y",
                IS_PRIMARY_KEY: "N",
                IS_ROW_TITLE: "N",
            },
        ],
    },
};
